name: Build

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: list files
      run: export C_FILES=`find . -type f -name '*.c'`
    - name: Build
      run: for file in $(find . -type f -name '*.c') ;
            do
              gcc -o $(echo $file | sed 's/..$//') "$file";
            done
